[PARSER]
    Name        json
    Format      json
    Time_Key    timestamp
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    Time_Keep   On

[PARSER]
    Name         apache2
    Format       regex
    Regex        ^(?<remote>[^ ]*) [^ ]* [^ ]* \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^"]*?)(?: +\S*)?)?" (?<status>\d{3}) (?<bytes>\d+|-) "(?<referer>[^"]*)" "(?<agent>[^"]*)"(?: "(?<forwarded>[^"]*)")?$
    Time_Key     time
    Time_Format  %d/%b/%Y:%H:%M:%S %z
