apiVersion: 1

datasources:
  - name: SIEM-OpenSearch
    type: elasticsearch
    access: proxy
    url: http://siem:9200
    database: wazuh-alerts-*
    jsonData:
      timeField: "@timestamp"
      interval: Daily
      esVersion: 80
      maxConcurrentShardRequests: 5
